name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Jalankan workflow setiap kali ada push ke branch "main"
  pull_request:
    branches:
      - main # Jalankan workflow setiap kali ada PR ke branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Mengambil kode dari repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Mengatur Docker Buildx untuk membangun image

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Menggunakan secrets untuk username Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }} # Menggunakan secrets untuk password Docker Hub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Lokasi source code
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/locust:latest # Nama Docker image di Docker Hub

  deploy:
    runs-on: ubuntu-latest
    needs: build # Pastikan deploy dijalankan setelah build selesai

    steps:
      - name: Deploy to server via SSH with password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }} # Host server
          username: ${{ secrets.SERVER_USER }} # Username SSH server
          password: ${{ secrets.SERVER_PASSWORD }} # Password SSH server
          port: ${{ secrets.SERVER_PORT }} # Port SSH server
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/locust:latest
            docker stop locust || true
            docker rm locust || true
            docker run -d -p 8089:8089 --name locust ${{ secrets.DOCKER_USERNAME }}/locust:latest
